### ISSUE TITLE
Display not showing anything

### ISSUE THREAD

**Issue by GaWr26** [r-cute/rcute-cozmars-server#25]
Hi again,

today i found some time to take a look at cozmars v2 again.
After finding out I hd to rewire the mic, the webserver starts as expected.
Servos, microphone and speaker work.

I can't get the display to work though. I've checked the wiring multiple times and the backlight comes on.
By using dim controls I can see it changes the backlight. Just nothing displayed.

I'm really lost here as I don't know where to look next. Any ideas or methods on how I could test only the display easily?

Cheers

**Comment by GaWr26** [comment]
Quick update, my display is functioning as I successfully tried it following this article: https://learn.adafruit.com/adafruit-1-14-240x135-color-tft-breakout/python-wiring-and-setup I was able to display a jpeg...

Unfortunately with cozmars it stays black. Using the Web Interface to change color doesn't do anything. Brightness works. 
Using the Python SDK has the same result. It turns on but doesn't display the eyes...

**Comment by hyansuper** [comment]
Any error message？
Can you test the adafruit example with cozmars pin connection？

**Comment by GaWr26** [comment]
By trying your idea I figured I had a loose wire. Soldered it back and now it works. 
Thanks for getting back! I will keep you updated on my progress.

I'm fed with my jumper wires. They always come loose. I will need to find a better solution...

My plan is to connect cozmars with my Homeassistant and e.g. announce when someone is at the door

**Comment by hyansuper** [comment]
Interesting！so I guess you install HA on a Raspberry pi and the pi also controls cozmars？

**Comment by GaWr26** [comment]
You got it! 
I have homeassistant running on my pi4 (4GB) and this should then also host the python script to control cozmars. 
But before that, I need to get him back together. It's really tight in there and I'm a bit scared :)

Once I have something to show i will make a video. Can you see youtube? i already made a nice video for v1 when I got it working...

**Comment by hyansuper** [comment]
Yes I saw the video. It's a nice print
